services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: school_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./Backend:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - school_network

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    container_name: school_frontend
    restart: unless-stopped
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - school_network

  postgres:
    image: postgres:17-alpine
    container_name: school_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: school_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - school_network

networks:
  school_network:

volumes:
  postgres_data:
